// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prdmtlvixvlsdkyvxzmt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByZG10bHZpeHZsc2RreXZ4em10Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMDI3NzQsImV4cCI6MjA2ODY3ODc3NH0.z-Gaph15vwHaXGN3tipKyQo7KbY7StyFDD-tNlxtUDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});