// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmzojirrthhjuppdfgfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imttem9qaXJydGhoanVwcGRmZ2ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI5NDE5MjMsImV4cCI6MjA2ODUxNzkyM30.55Zic7TjSK9Rzc3uMSXWUeBNW9QxFtKrkYpNs5v_AYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});